Repository hanium-4ward/Diarist, pull requests merged in 2024-06, with the labels that each got.

#16 markup : PROJ-67 : 화가리스트 페이지 마크업
  web/src/App.jsx
  web/src/pages/DrawerListPage.jsx
Labels: 🎨 Html&Css

#17 markup : PROJ-71 : 화가정보 모달창 마크업
  web/.eslintrc.json
  web/index.html
  web/src/components/CheckModal.jsx
  web/src/components/DrawerModal.jsx
  web/src/pages/DrawerListPage.jsx
Labels: 🎨 Html&Css

#20 feat : PROJ-104 : 카프카를 통한 ai 서버에 그림일기 요청 메세지큐 전송 로직 구현
  server/Spring/.gitignore
  server/Spring/build.gradle
  server/Spring/src/main/java/com/hanium/diarist/common/config/KafkaProducerConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/config/WebConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/validator/DiaryDateValidator.java
  server/Spring/src/main/java/com/hanium/diarist/common/validator/ValidDiaryDate.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Diary.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Image.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/AdResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/CreateDiaryRequest.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/repository/DiaryRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerService.java
  server/Spring/src/main/resources/application-dev.yml
  server/Spring/src/main/resources/application-kafka.yml
  server/Spring/src/main/resources/application-test.yml
  server/Spring/src/main/resources/application.yml
Labels: 📞 API, ⭐️ Feature, ⚙️ Setting

#18 markup : PROJ-16 : 페이지별 마크업
  web/src/App.jsx
  web/src/pages/AlbumListPage.jsx
  web/src/pages/AlbumThumbnailPage.jsx
Labels: 🎨 Html&Css

#22 feat : PROJ-98 : 즐겨찾기 로직 구현
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Diary.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/BookmarkDiaryRequest.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/BookmarkDiaryResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/repository/DiaryRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/DiaryService.java
Labels: ⭐️ Feature, 🛠️ Refactor

#23 Style : PROJ-65 : 화가 완성 페이지 스타일
  web/index.html
  web/src/components/DrawerModal.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/DrawerListPage.jsx
  web/src/pages/SelectDrawerPage.jsx
  web/vite.config.js
Labels: 🎨 Html&Css

#24 refactor : PROJ-113 : 일기 생성 완료 메세지를 받아 클라이언트에게 제공하는 로직 수정
  server/Spring/src/main/java/com/hanium/diarist/common/exception/BusinessException.java
  server/Spring/src/main/java/com/hanium/diarist/common/exception/ErrorCode.java
  server/Spring/src/main/java/com/hanium/diarist/common/exception/GlobalExceptionHandler.java
  server/Spring/src/main/java/com/hanium/diarist/common/response/ErrorResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Diary.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Image.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/exception/DiaryIdInvalidException.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/exception/DiaryNotFoundException.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/exception/JsonProcessException.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/exception/KafkaConnectException.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/exception/SseException.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/repository/DiaryRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryConsumerService.java
Labels: 🛠️ Refactor

#28 feat : PROJ-16 : 페이지 별 마크업
  web/.gitignore
  web/package-lock.json
  web/pnpm-lock.yaml
  web/public/back.png
  web/public/btn_x.png
  web/public/close.png
  web/public/diary.webp
  web/public/emotion.png
  web/public/listFalse.png
  web/public/listTrue.png
  web/public/thumbnailFalse.png
  web/public/thumbnailTrue.png
  web/public/toggle.svg
  web/src/App.jsx
  web/src/components/ButtonContainer.jsx
  web/src/components/Emotion.jsx
  web/src/components/ListAlbum.jsx
  web/src/components/ThumbnailAlbum.jsx
  web/src/components/TopNavBar.jsx
  web/src/pages/AlbumListPage.jsx
  web/src/pages/AlbumThumbnailPage.jsx
  web/src/pages/Calendar.jsx
  web/src/pages/SelectDrawerPage.jsx
  web/src/pages/SelectEmotionPage.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: ⭐️ Feature, 🎨 Html&Css

#25 refactor : PROJ-114 : 일기 생성 요청을 kafka에 보내는 로직 리팩토링
  server/Spring/src/main/java/com/hanium/diarist/common/config/KafkaProducerConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/response/SuccessResponse.java
  server/Spring/src/main/java/com/hanium/diarist/common/validator/DiaryDateValidator.java
  server/Spring/src/main/java/com/hanium/diarist/common/validator/ValidDiaryDate.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/controller/ArtistController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/DiaryService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/controller/EmotionController.java
Labels: 🛠️ Refactor

#30 styling : PROJ-65 : 일기 확인 페이지 스타일링
  web/.gitignore
  web/pnpm-lock.yaml
  web/public/btn_prev.png
  web/public/btn_x.png
  web/public/fullStar.png
  web/public/vite.svg
  web/public/woff2/PretendardVariable.woff2
  web/src/App.css
  web/src/App.jsx
  web/src/GlobalStyle.jsx
  web/src/assets/back.png
  web/src/assets/btn_prev.png
  web/src/assets/close.png
  web/src/assets/fonts/Pretendard-Black.otf
  web/src/assets/fonts/Pretendard-Bold.otf
  web/src/assets/fonts/Pretendard-ExtraBold.otf
  web/src/assets/fonts/Pretendard-ExtraLight.otf
  web/src/assets/fonts/Pretendard-Light.otf
  web/src/assets/fonts/Pretendard-Medium.otf
  web/src/assets/fonts/Pretendard-Regular.otf
  web/src/assets/fonts/Pretendard-SemiBold.otf
  web/src/assets/fonts/Pretendard-Thin.otf
  web/src/assets/react.svg
  web/src/components/TopNavBar.jsx
  web/src/pages/Calendar.jsx
  web/src/pages/DrawCompletedPage.jsx
Labels: 🎨 Html&Css

#32 feat : PROJ-16 : 페이지 별 마크업
  web/src/GlobalStyle.jsx
  web/src/components/ButtonContainer.jsx
  web/src/components/Emotion.jsx
  web/src/pages/SelectEmotionPage.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: ⭐️ Feature, 🎨 Html&Css

#33 refactor : PROJ-115 : 일기 생성 요청을 kafka에 보내는 로직의 Test Code 작성
  server/Spring/build.gradle
  server/Spring/src/main/java/com/hanium/diarist/common/exception/ErrorCode.java
  server/Spring/src/main/java/com/hanium/diarist/common/exception/GlobalExceptionHandler.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerService.java
  server/Spring/src/test/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerServiceTest.java
Labels: 🛠️ Refactor, 🎲 Test

#34 feat : PROJ-116 : 즐겨찾기 로직 TestCode 작성
  server/Spring/src/test/java/com/hanium/diarist/domain/diary/service/DiaryServiceTest.java
Labels: 🎲 Test

#36 chore : PROJ-94 : 장고 어플리케이션을 위한 도커 환경 구축
  model/Dockerfile
  model/requirements.txt
Labels: ⚙️ Setting

#37 styling : PROJ-67 : 화가리스트 페이지 스타일링
  web/index.html
  web/public/PretendardVariable.woff2
  web/src/GlobalStyle.jsx
  web/src/components/CategoryButton.jsx
  web/src/components/CheckModal.jsx
  web/src/components/DrawerModal.jsx
  web/src/components/TopNavBar.jsx
  web/src/font.css
  web/src/pages/Calendar.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/DrawerListPage.jsx
  web/src/pages/SelectDrawerPage.jsx
  web/vite.config.js
Labels: 🎨 Html&Css

#40 feat : PROJ-87 : API 서버로 부터 받은 일기 데이터를 AI 모델에 전달한다.
  model/Dockerfile
  model/diary/consumer/__init__.py
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
  model/docker-compose.yml
Labels: ⭐️ Feature, ⚙️ Setting

#41 feat : PROJ-67 : 화가선택, 화가 리스트 모달창 스타일링 및 기능 구현
  web/src/components/CheckModal.jsx
  web/src/components/CompleteButton.jsx
  web/src/components/TopNavBar.jsx
  web/src/components/bottomsheet/BottomSheet.jsx
  web/src/components/bottomsheet/BottomSheetHeader.jsx
  web/src/components/bottomsheet/DrawerBottomSheet.jsx
  web/src/hooks/useBottomSheet.jsx
  web/src/pages/DrawDetailPage.jsx
  web/src/pages/DrawerListPage.jsx
  web/src/pages/SelectDrawerPage.jsx
Labels: ⭐️ Feature, 🎨 Html&Css

#43 feat : PROJ-111 : 일기 데이터를 RDB 및 S3에 저장
  model/config/settings.py
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
  model/diary/models.py
  model/diary/utils.py
  model/requirements.txt
Labels: ⭐️ Feature

#45 feat : PROJ-16 : 버튼 비활성화 구현
  app/package-lock.json
  app/package.json
  web/public/angry.png
  web/public/annoy.png
  web/public/excite.png
  web/public/expect.png
  web/public/flutter.png
  web/public/fun.png
  web/public/happy.png
  web/public/regret.png
  web/public/sad.png
  web/public/thank.png
  web/public/tired.png
  web/public/worry.png
  web/src/components/DiaryButton.jsx
  web/src/components/DrawerModal.jsx
  web/src/components/Emotion.jsx
  web/src/components/EmotionButton.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/SelectEmotionPage.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: ⭐️ Feature, 🎨 Html&Css

#44 feat : PROJ-117 : 일기 데이터가 저장완료되면 카프카로 일기 작성완료 메세지 보내기
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
Labels: ⭐️ Feature

#46 docs : PROJ-51 : PR 템플릿에 Jira 티켓 예시 추가
  .github/pull_request_template.md
Labels: 📑 Docs
