Repository hanium-4ward/Diarist, pull requests merged in 2024-05, with the labels that each got.

#1 docs : PROJ-51 : PR template 및 CODEOWNERS 생성
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: 📑 Docs

#2 docs : PROJ-51 : PR template 작업유형 항목 추가
  .github/pull_request_template.md
Labels: 📑 Docs

#3 feat: PROJ-54 : Spring Project 생성
  server/Spring/.gitignore
  server/Spring/build.gradle
  server/Spring/gradle/wrapper/gradle-wrapper.jar
  server/Spring/gradle/wrapper/gradle-wrapper.properties
  server/Spring/gradlew
  server/Spring/gradlew.bat
  server/Spring/settings.gradle
  server/Spring/src/main/java/com/hanium/diarist/DiaristApplication.java
  server/Spring/src/main/resources/application.properties
  server/Spring/src/test/java/com/hanium/diarist/DiaristApplicationTests.java
Labels: ⚙️ Setting

#4 feat: PROJ-52 : 리액트 네이티브, 리액트 프로젝트 생성
  app/.gitignore
  app/App.js
  app/app.json
  app/assets/adaptive-icon.png
  app/assets/favicon.png
  app/assets/icon.png
  app/assets/splash.png
  app/babel.config.js
  app/package-lock.json
  app/package.json
  web/.eslintrc.cjs
  web/.gitignore
  web/README.md
  web/index.html
  web/package.json
  web/pnpm-lock.yaml
  web/postcss.config.js
  web/public/vite.svg
  web/reset.css
  web/src/App.css
  web/src/App.jsx
  web/src/assets/react.svg
  web/src/index.css
  web/src/main.jsx
  web/tailwind.config.js
  web/vite.config.js
Labels: ⚙️ Setting

#5 feat: PROJ-52 : front 프로젝트 세팅
  web/.eslintrc.cjs
  web/.eslintrc.json
  web/.prettierrc
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.jsx
  web/src/index.css
Labels: ⚙️ Setting

#6 feat: PROJ-95 : Django 프로젝트 생성
  model/.gitignore
  model/config/__init__.py
  model/config/asgi.py
  model/config/settings.py
  model/config/urls.py
  model/config/wsgi.py
  model/manage.py
  model/requirements.txt
Labels: ⚙️ Setting

#7 feat: PROJ-52 : 리액트 네이티브 디렉토리 구조 변경 및 폰트 적용
  app/App.js
  app/app.json
  app/index.js
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/assets/adaptive-icon.png
  app/src/assets/favicon.png
  app/src/assets/fonts/Pretendard-Black.otf
  app/src/assets/fonts/Pretendard-Bold.otf
  app/src/assets/fonts/Pretendard-ExtraBold.otf
  app/src/assets/fonts/Pretendard-ExtraLight.otf
  app/src/assets/fonts/Pretendard-Light.otf
  app/src/assets/fonts/Pretendard-Medium.otf
  app/src/assets/fonts/Pretendard-Regular.otf
  app/src/assets/fonts/Pretendard-SemiBold.otf
  app/src/assets/fonts/Pretendard-Thin.otf
  app/src/assets/icon.png
  app/src/assets/splash.png
  app/src/hooks/useFont.js
  web/pnpm-lock.yaml
  web/src/App.jsx
Labels: ⚙️ Setting

#8 feat : PROJ-52 : 리액트네이티브 코딩컨벤션 적용
  app/.eslintrc.json
  app/.prettierrc
  app/package.json
  app/pnpm-lock.yaml
  app/src/App.js
Labels: ⚙️ Setting

#9 feat : PROJ-99 : 테스트용 유저 생성 로직 구현
  .DS_Store
  server/.DS_Store
  server/Spring/.gitignore
  server/Spring/build.gradle
  server/Spring/src/main/java/com/hanium/diarist/DiaristApplication.java
  server/Spring/src/main/java/com/hanium/diarist/common/config/DotenvConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/entity/BaseEntity.java
  server/Spring/src/main/java/com/hanium/diarist/common/entity/BaseEntityWithUpdate.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/controller/UserController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/domain/SocialCode.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/domain/User.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/domain/UserRole.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/dto/UserRegistrationRequest.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/repository/UserRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/service/UserService.java
  server/Spring/src/main/resources/application-dev.yml
  server/Spring/src/main/resources/application.properties
Labels: ⭐️ Feature

#10 feat : PROJ-52 : useFont hook 추가 및 eslint에 맞춰 코드 변경
  app/.eslintrc.json
  app/index.js
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/hooks/useFont.js
Labels: 🛠️ Refactor

#11 feat : PROJ-103 : 감정 테이블 생성 및 등록 로직 구현
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/controller/EmotionController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/domain/Emotion.java
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/dto/CreateEmotionRequest.java
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/dto/CreateEmotionResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/repository/EmotionRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/emotion/service/EmotionService.java
Labels: ⭐️ Feature

#12 feat : PROJ-62 : 웹 확인을 위한 라우터 설정 및 일기 작성 페이지 마크업
  app/package-lock.json
  app/package.json
  app/pnpm-lock.yaml
  web/package-lock.json
  web/package.json
  web/pnpm-lock.yaml
  web/public/back.png
  web/public/btn_prev.png
  web/public/close.png
  web/src/App.jsx
  web/src/assets/back.png
  web/src/assets/btn_prev.png
  web/src/assets/close.png
  web/src/main.jsx
  web/src/pages/Calendar.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: ⚙️ Setting

#14 feat : PROJ-24 : 화가 생성, 조회 API 생성
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/controller/ArtistController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/domain/Artist.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/domain/Period.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/dto/ArtistFilterByPeriodResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/dto/CreateArtistRequest.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/dto/CreateArtistResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/repository/ArtistRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/service/ArtistService.java
Labels: ⭐️ Feature

#15 markup : PROJ-16 : 화가 선택 페이지, 일기 확인 페이지 마크업
  web/pnpm-lock.yaml
  web/public/drawer.jpg
  web/public/prev.png
  web/public/star.png
  web/src/App.jsx
  web/src/pages/Calendar.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/SelectDrawerPage.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: 🎨 Html&Css
