Repository hanium-4ward/Diarist, pull requests merged in 2024-08, with the labels that each got.

#81 feat : PROJ-29 : 데모 시연
  app/src/MyStack.js
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/SelectDrawerPage.jsx
Labels: ⭐️ Feature

#82 feat : PROJ-38 : 하단 네비게이션바 생성 및 앨범 페이지 연결
  app/src/MyStack.js
  app/src/MyTab.js
  app/src/assets/albumIcon.png
  app/src/assets/artistIcon.png
  app/src/assets/calendarIcon.png
  app/src/assets/myPageIcon.png
  app/src/assets/writeIcon.png
  app/src/pages/AlbumWebView.js
  app/src/pages/Calendar.js
  app/src/pages/KakaoLoginRedirect.js
  web/src/pages/AlbumPage.jsx
Labels: 📞 API, ⭐️ Feature

#83 feat : PROJ-17 : DALL-E 3 모델에 전달하는 프롬프트를 직접 생성해서 이미지 생성하도록 수정
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
  model/diary/models.py
Labels: 📞 API, ⭐️ Feature

#84 feat : PROJ-17 : 그림 일기 생성 로직을 Celery를 사용한 비동기 작업 처리로 변경
  model/.dockerignore
  model/config/celery.py
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
  model/diary/tasks.py
  model/docker-compose.yml
  model/requirements.txt
Labels: 📞 API, ⭐️ Feature, 🛠️ Refactor

#85 feat : PROJ-38 : 하단 네비게이션바와 페이지 연결
  app/src/MyStack.js
  app/src/MyTab.js
  app/src/pages/ArtistWebView.js
  app/src/pages/WriteDiaryWebView.js
  web/src/pages/AlbumPage.jsx
Labels: 📞 API, ⭐️ Feature

#86 feat : PROJ-17 : RDS, S3에 저장할 때 동시 접근 문제 방지하기 위해 Redis를 활용한 분산 락 기능 추가
  model/config/settings.py
  model/diary/tasks.py
  model/diary/utils/redis_lock.py
  model/diary/utils/s3_uploader.py
Labels: ⭐️ Feature, 🛠️ Refactor

#87 feat : PROJ-41 : SonarQube를 참고한 API 서버 코드 리팩토링
  model/.gitignore
  server/Spring/build.gradle
  server/Spring/src/main/java/com/hanium/diarist/DiaristApplication.java
  server/Spring/src/main/java/com/hanium/diarist/common/config/KafkaConsumerConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/resolver/AuthUserArgumentResolver.java
  server/Spring/src/main/java/com/hanium/diarist/common/security/jwt/JwtProperties.java
  server/Spring/src/main/java/com/hanium/diarist/common/security/jwt/JwtTokenProvider.java
  server/Spring/src/main/java/com/hanium/diarist/common/validator/DiaryDateValidator.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/controller/ArtistController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/domain/Artist.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/domain/Period.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Diary.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/domain/Image.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/controller/OAuthController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/KakaoOauthService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/controller/UserController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/service/UserService.java
  server/Spring/src/main/resources/application-dev.yml
  server/Spring/src/main/resources/application-test.yml
  server/Spring/src/main/resources/application.yml
  server/Spring/src/test/java/com/hanium/diarist/DiaristApplicationTests.java
  server/Spring/src/test/java/com/hanium/diarist/common/config/TestEnvironmentConfig.java
  server/Spring/src/test/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerServiceTest.java
  server/Spring/src/test/java/com/hanium/diarist/domain/diary/service/DiaryServiceTest.java
Labels: 🛠️ Refactor, ⚙️ Setting, 🎲 Test

#88 fix : PROJ-171 : S3와 RDS 접근 시 동시성 제어를 위한 분산 락 lock name 수정 및 최적화
  model/diary/tasks.py
Labels: 🕷️ Bugfix, ⭐️ Feature

#89 feat : PROJ-26 : GitAction을 통한 CI/CD 구축
  .github/workflows/serverGitAction.yml
  server/Spring/.gitignore
  server/Spring/src/main/java/com/hanium/diarist/DiaristApplication.java
  server/Spring/src/main/java/com/hanium/diarist/common/config/DotenvConfig.java
  server/Spring/src/main/resources/application-aws.yml
  server/Spring/src/main/resources/application-kafka.yml
  server/Spring/src/main/resources/application-oauth.yml
  server/Spring/src/main/resources/application.yml
  server/Spring/src/test/java/com/hanium/diarist/DiaristApplicationTests.java
  server/Spring/src/test/java/com/hanium/diarist/common/config/TestEnvironmentConfig.java
Labels: 🛠️ Refactor, ⚙️ Setting

#90 fix : PROJ-132 : gitaction 파일 수정
  .github/workflows/serverGitAction.yml
Labels: 🕷️ Bugfix, 🌏 Deploy

#91 feat : PROJ-42 : 유저의 오늘 일기 작성 여부 확인 api
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/CreateDiaryResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/TodayDiaryResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/repository/DiaryRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/DiaryService.java
Labels: 📞 API, ⭐️ Feature

#92 feat : PROJ-18 : GitHub Actions 워크플로우를 통한 Docker 이미지 빌드, 푸시 및 EC2 배포 자동화
  .github/workflows/ai_gitaction.yml
  model/Dockerfile
  model/docker-compose.yml
Labels: 🌏 Deploy

#94 refactor : PROJ-132 : server 디렉토리에 변경사항이 있을때만 작동
  .github/workflows/serverGitAction.yml
Labels: 🌏 Deploy, 🛠️ Refactor

#93 feat : PROJ-41 : api 서버의 부가적 기능 추가
  server/Spring/build.gradle
  server/Spring/src/main/java/com/hanium/diarist/common/config/SecurityConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/log/MDCRequestLoggingFilter.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryConsumerService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/DiaryService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/health/controller/HealthCheckController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/KakaoOauthService.java
  server/Spring/src/main/resources/logback-spring.xml
Labels: 📞 API, ⭐️ Feature, 🛠️ Refactor

#95 fix : PROJ-135 : GitHub Actions에서 Docker Compose 명령어 및 AWS 관련 오류 수정
  .github/workflows/ai_gitaction.yml
Labels: 🕷️ Bugfix, 🌏 Deploy

#96 fix : PROJ-26 : resources 디렉토리 생성으로 인한 gitaction.yml 파일 수정
  .github/workflows/serverGitAction.yml
Labels: 🕷️ Bugfix, 🌏 Deploy

#97 refactor : PROJ-18 : EC2 인스턴스 디스크 공간 확보를 위해 CICD 파이프라인에 Docker 이미지 자동 삭제 추가
  .github/workflows/ai_gitaction.yml
Labels: 🌏 Deploy, 🛠️ Refactor

#99 PROJ-39 : 설정 페이지 생성 및 알람 설정
  app/package-lock.json
  app/package.json
  app/pnpm-lock.yaml
  app/src/MyStack.js
  app/src/MyTab.js
  app/src/assets/btn_x.png
  app/src/assets/setting.jpeg
  app/src/pages/Alert.js
  app/src/pages/Calendar.js
  app/src/pages/KakaoWebView.js
  app/src/pages/Setting.js
  app/src/pages/WriteDiaryWebView.js
  web/src/pages/SelectDrawerPage.jsx
  web/src/pages/SelectEmotionPage.jsx
Labels: ⭐️ Feature

#100 feat : PROJ-37 : 웹 뷰 S3 배포
  .github/workflows/frontGitAction.yml
  web/public/angry.png
  web/public/annoy.png
  web/public/diary.webp
  web/public/drawer.jpg
  web/public/emotion.png
  web/public/excite.png
  web/public/expect.png
  web/public/flutter.png
  web/public/fun.png
  web/public/happy.png
  web/public/regret.png
  web/public/sad.png
  web/public/thank.png
  web/public/tired.png
  web/public/worry.png
  web/public/완성이미지.png
  web/public/피카소.png
  web/src/components/CompleteButton.jsx
  web/src/components/TopNavBar.jsx
  web/src/components/bottomsheet/DrawerBottomSheet.jsx
  web/src/hooks/useApi.jsx
  web/src/pages/AlbumPage.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/DrawDetailPage.jsx
  web/src/pages/DrawerListPage.jsx
  web/src/pages/SelectDrawerPage.jsx
Labels: 🌏 Deploy

#101 refactor : PROJ-17 : 프롬프트 구조를 기본, 스타일, 상세 설명으로 세분화
  model/diary/tasks.py
Labels: 🛠️ Refactor

#102 docs : PROJ-26 : actuator 관련 yml 파일을 gitignore 에 추가
  server/Spring/.gitignore
Labels: 📑 Docs, ⚙️ Setting

#103 refactor : PROJ-41 : artist DB에 컬럼 추가
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/domain/Artist.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/dto/CreateArtistRequest.java
  server/Spring/src/test/java/com/hanium/diarist/domain/diary/service/DiaryServiceTest.java
Labels: 🛠️ Refactor

#104 feat : PROJ-17 : 그림 생성 시 Dalle-3 외에 Stable Diffusion 모델 추가 적용
  model/Dockerfile
  model/config/settings.py
  model/diary/models.py
  model/diary/tasks.py
  model/requirements.txt
Labels: 🕷️ Bugfix, ⭐️ Feature, 🛠️ Refactor

#105 fix : PROJ-182 : 프롬프트 keywords 오류 수정
  model/diary/tasks.py
Labels: 🕷️ Bugfix
