Repository hanium-4ward/Diarist, pull requests merged in 2024-07, with the labels that each got.

#49 feat : PROJ-19 : 구글 로그인, 회원 탈퇴 , 로그아웃 기능 구현
  server/Spring/src/main/java/com/hanium/diarist/DiaristApplication.java
  server/Spring/src/main/java/com/hanium/diarist/common/config/SecurityConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/config/WebConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/exception/ErrorCode.java
  server/Spring/src/main/java/com/hanium/diarist/common/resolver/AuthUser.java
  server/Spring/src/main/java/com/hanium/diarist/common/resolver/AuthUserArgumentResolver.java
  server/Spring/src/main/java/com/hanium/diarist/common/security/jwt/JwtTokenInfo.java
  server/Spring/src/main/java/com/hanium/diarist/common/security/jwt/JwtTokenProvider.java
  server/Spring/src/main/java/com/hanium/diarist/common/utils/HeaderUtils.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/controller/OAuthController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/domain/Auth.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/dto/GoogleAccessToken.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/dto/GoogleUserProfile.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/dto/KakaoUserProfile.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/exception/OAuthNotFoundException.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/properties/GoogleProperties.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/properties/KakaoProperties.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/repository/AuthRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/GoogleOauthService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/KakaoOauthService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/OAuthService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/service/UserService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/service/ValidateUserService.java
  server/Spring/src/main/resources/application-oauth.yml
Labels: 📞 API, ⭐️ Feature, 🛠️ Refactor

#50 fix : PROJ-19 : 카카오 회원 가입시 구글 이메일과 중복될 경우 회원가입 오류 수정
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/GoogleOauthService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/KakaoOauthService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/repository/UserRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/user/service/ValidateUserService.java
Labels: 🕷️ Bugfix

#52 fix : PROJ-19 : jwt를 받을 때 dto를 통해 받도록 재설정
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/controller/OAuthController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/dto/AuthorizationCode.java
Labels: 🕷️ Bugfix

#59 feat : PROJ-30 : 일기 재생성 요청 시 S3에 저장되어있던 기존 이미지 URL도 삭제되도록 로직 재구현
  model/diary/consumer/re_create_diary_consumer.py
  model/diary/utils.py
Labels: ⭐️ Feature

#53 feat: PROJ-152 : 앨범 페이지 마크업 및 스타일링, 보기 아이콘 기능 추가
  web/public/BlackStar.png
  web/public/CheckBox.png
  web/src/App.jsx
  web/src/components/ListAlbum.jsx
  web/src/components/ThumbnailAlbum.jsx
  web/src/pages/AlbumListPage.jsx
  web/src/pages/AlbumPage.jsx
  web/src/pages/AlbumThumbnailPage.jsx
  web/src/pages/Calendar.jsx
Labels: ⭐️ Feature, 🎨 Html&Css

#56 feat : PROJ-28 : 로그인 페이지 스타일링 및 카카오 소셜 로그인 구현
  app/.eslintrc.json
  app/.gitignore
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/MyStack.js
  app/src/assets/googleicon.png
  app/src/assets/kakaoicon.png
  app/src/pages/KakaoLoginRedirect.js
  app/src/pages/KakaoWebView.js
  app/src/pages/Login.js
  app/src/pages/Test.js
Labels: 🕷️ Bugfix, ⭐️ Feature, 🎨 Html&Css

#62 feat : PROJ-20 : 캘린더 페이지에 사용될 api 개발
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/DiaryListResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/repository/DiaryRepository.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/DiaryService.java
  server/Spring/src/test/java/com/hanium/diarist/domain/diary/service/DiaryServiceTest.java
Labels: 📞 API, ⭐️ Feature

#63 feat : PROJ-19 : JwtAuthenticationEntryPoint 추가
  server/Spring/src/main/java/com/hanium/diarist/common/config/SecurityConfig.java
  server/Spring/src/main/java/com/hanium/diarist/common/security/jwt/JwtAuthenticationEntryPoint.java
Labels: ⭐️ Feature, 🛠️ Refactor

#64 refactor : PROJ-19 : google 로그인 로직 수정
  server/Spring/src/main/java/com/hanium/diarist/common/config/SecurityConfig.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/controller/OAuthController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/oauth/service/GoogleOauthService.java
Labels: 📞 API, ⭐️ Feature, 🛠️ Refactor

#65 feat : PROJ-32 : 앨범 페이지 통신 및 기능 구현
  web/src/components/ListAlbum.jsx
  web/src/pages/AlbumPage.jsx
  web/src/pages/Calendar.jsx
Labels: 📞 API, ⭐️ Feature

#66 feat : PROJ-28 : 토큰 디코딩을 통한 토큰 재발급 여부 확인
  app/.gitignore
  app/android/.gitignore
  app/android/app/build.gradle
  app/android/app/debug.keystore
  app/android/app/proguard-rules.pro
  app/android/app/src/debug/AndroidManifest.xml
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/java/com/diarist/app/MainActivity.kt
  app/android/app/src/main/java/com/diarist/app/MainApplication.kt
  app/android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  app/android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  app/android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  app/android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  app/android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  app/android/app/src/main/res/drawable/rn_edit_text_material.xml
  app/android/app/src/main/res/drawable/splashscreen.xml
  app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/android/app/src/main/res/values-night/colors.xml
  app/android/app/src/main/res/values/colors.xml
  app/android/app/src/main/res/values/strings.xml
  app/android/app/src/main/res/values/styles.xml
  app/android/build.gradle
  app/android/gradle.properties
  app/android/gradle/wrapper/gradle-wrapper.jar
  app/android/gradle/wrapper/gradle-wrapper.properties
  app/android/gradlew
  app/android/gradlew.bat
  app/android/settings.gradle
  app/app.json
  app/babel.config.js
  app/eas.json
  app/package-lock.json
  app/package.json
  app/src/App.js
  app/src/MyStack.js
  app/src/context/AuthContext.js
  app/src/hooks/useApi.js
  app/src/pages/GoogleRedirect.js
  app/src/pages/GoogleWebView.js
  app/src/pages/KakaoLoginRedirect.js
  app/src/pages/KakaoWebView.js
  app/src/pages/Login.js
  app/src/pages/Test.js
Labels: 📞 API, ⭐️ Feature

#67 feat : PROJ-29 : 캘린더 통신 테스트
  app/package-lock.json
  app/package.json
  app/src/MyStack.js
  app/src/assets/Plus.png
  app/src/hooks/useApi.js
  app/src/hooks/useApiTest.js
  app/src/pages/Calendar.js
  app/src/pages/KakaoLoginRedirect.js
Labels: 📞 API

#68 feat : PROJ-35 : 캘린더 페이지에서 + 버튼을 누르면 웹뷰로 이동
  app/.eslintrc.json
  app/babel.config.js
  app/package-lock.json
  app/package.json
  app/src/MyStack.js
  app/src/context/AuthContext.js
  app/src/hooks/useApi.js
  app/src/pages/Calendar.js
  app/src/pages/GoogleRedirect.js
  app/src/pages/KakaoLoginRedirect.js
  app/src/pages/KakaoWebView.js
  app/src/pages/Login.js
  app/src/pages/Test.js
  app/src/pages/WriteDiaryWebView.js
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/TopNavBar.jsx
  web/src/pages/DrawCompletedPage.jsx
Labels: 📞 API, 🕷️ Bugfix, ⭐️ Feature

#69 feat : PROJ-30 : AI 서버에서 카프카로 일기 작성완료 메세지를 보낼 때 메세지에 user_id 데이터 추가
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
Labels: ⭐️ Feature

#70 fix : PROJ-30 : 일기 생성 요청 수정
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/controller/DiaryController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/CreateDiaryRequest.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/dto/CreateDiaryResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryConsumerService.java
  server/Spring/src/main/java/com/hanium/diarist/domain/diary/service/CreateDiaryProducerService.java
Labels: 📞 API, 🕷️ Bugfix, 🛠️ Refactor

#72 feat : PROJ-30 : 그림 이미지를 생성하기 위한 사용자로 부터 입력받은 일기 데이터 전처리 및 텍스트 생성
  model/Dockerfile
  model/diary/consumer/create_diary_consumer.py
  model/diary/consumer/re_create_diary_consumer.py
  model/requirements.txt
Labels: 📑 Docs, ⭐️ Feature

#73 feat : PROJ-36 : 뒤로가기 클릭 시 기존 데이터 남아있도록 수정
  web/package-lock.json
  web/src/App.jsx
  web/src/components/DiaryButton.jsx
  web/src/components/EmotionButton.jsx
  web/src/hooks/DiaryContext.jsx
  web/src/pages/SelectEmotionPage.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: ⭐️ Feature

#74 refactor : PROJ-166 : 화가 리스트 , 화가 선택 페이지 API 수정
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/controller/ArtistController.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/dto/ArtistFilterByPeriodResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/dto/SelectArtistResponse.java
  server/Spring/src/main/java/com/hanium/diarist/domain/artist/service/ArtistService.java
Labels: 📞 API, 🛠️ Refactor

#76 feat : PROJ-35 : 그림완성 로직 구현 후 랜더링
  app/src/context/AuthContext.js
  app/src/pages/KakaoLoginRedirect.js
  app/src/pages/WriteDiaryWebView.js
  web/package-lock.json
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.jsx
  web/src/components/CompleteButton.jsx
  web/src/components/bottomsheet/BottomSheet.jsx
  web/src/context/AuthContext.jsx
  web/src/context/DiaryContext.jsx
  web/src/hooks/useApi.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/SelectDrawerPage.jsx
  web/src/pages/SelectEmotionPage.jsx
  web/src/pages/WritingDiaryPage.jsx
Labels: 📞 API, ⭐️ Feature

#77 feat : PROJ-29 : 서버로 날짜 전달
  app/src/pages/Calendar.js
  web/package-lock.json
  web/pnpm-lock.yaml
  web/src/components/bottomsheet/BottomSheet.jsx
  web/src/context/DiaryContext.jsx
  web/src/pages/SelectEmotionPage.jsx
Labels: 📞 API

#78 feat : PROJ-29 : 그림 생성 후 바로 캘린더에 반영되도록 수정
  app/src/pages/Calendar.js
  app/src/pages/WriteDiaryWebView.js
  web/src/pages/DrawCompletedPage.jsx
Labels: ⭐️ Feature

#79 feat : PROJ-35 : 디테일 페이지 통신 작업
  app/package-lock.json
  app/package.json
  app/src/MyStack.js
  app/src/MyTab.js
  app/src/assets/logo.png
  app/src/pages/Calendar.js
  app/src/pages/DetailDiaryWebView.js
  app/src/pages/Login.js
  web/public/spinner.gif
  web/src/App.jsx
  web/src/components/CompleteButton.jsx
  web/src/components/Loading.jsx
  web/src/components/ResetModal.jsx
  web/src/components/TopNavBar.jsx
  web/src/hooks/useApi.jsx
  web/src/hooks/useBottomSheet.jsx
  web/src/pages/DrawCompletedPage.jsx
  web/src/pages/DrawDetailPage.jsx
  web/src/pages/DrawerListPage.jsx
  web/src/pages/SelectDrawerPage.jsx
  web/src/pages/SelectEmotionPage.jsx
Labels: 📞 API, ⭐️ Feature

#80 refactor : PROJ-111 : 일기 재성시 기존 이미지 레코드에 이미지 업데이트
  model/diary/consumer/re_create_diary_consumer.py
Labels: 🛠️ Refactor
